name: coastproc-notebooks
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - numpy
  - pip
  - pandas
  - scipy
  - scikit-image
  - scikit-learn=0.23
  - pip:
      - pybeach
      - matplotlib==3.3.4
